# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'react-native-ezplayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for react-native-ezplayer
  pod 'EZPlayer', :git =>'https://github.com/autumnyuhe/ezplayer.git'
	

end
